### ISSUE TITLE
MDN version could use a stronger contrast between focused and unfocused tabs

### ISSUE THREAD

**Issue by Coffeeling** [dhershman1/dusty-light#1]
Pretty much what it says on the tin, the contrast right now is quite low. Borderlines might be a decent solution as well.

**Comment by dhershman1** [comment]
Hey @Coffeeling do you mind checking out this screenshot and letting me know if the contrast is still pretty bad? I like the idea of the active tab being the same color as the main background. So I tried to stick with that.

https://prnt.sc/qbkrmw

**Comment by Coffeeling** [comment]
I'd go further than that, but comparing the screenshot and live side by side, that's a clear improvement in any case. If you're not averse to clear borderlines, those could be a good solution. The other option would be to change the color of the background tabs to have a stronger contrast the way browsers do.

**Comment by dhershman1** [comment]
Sorry this took so long, had a pretty busy holiday!

It doesn't seem like I can add separator borders, based on vscodes style documentation, so what I did was added a bottom border to the active tab, and I made the inactive tabs even lighter.

Thoughts @Coffeeling ?

https://prnt.sc/qg0757

**Comment by Coffeeling** [comment]
That looks amazing.

**Comment by dhershman1** [comment]
Great! This release should be out and ready for update on your vscode client. Thank you for your help!
